const conditonsData = [
  {
    code: 1000,
    day: "Ensolarado",
    night: "Céu limpo",
    icon: 113,
  },
  {
    code: 1003,
    day: "Parcialmente nublado",
    night: "Parcialmente nublado",
    icon: 116,
  },
  {
    code: 1006,
    day: "Nublado",
    night: "Nublado",
    icon: 119,
  },
  {
    code: 1009,
    day: "Encoberto",
    night: "Encoberto",
    icon: 122,
  },
  {
    code: 1030,
    day: "Neblina",
    night: "Neblina",
    icon: 143,
  },
  {
    code: 1063,
    day: "Possível chuva leve",
    night: "Possível chuva leve",
    icon: 176,
  },
  {
    code: 1066,
    day: "Possível neve leve",
    night: "Possível neve leve",
    icon: 179,
  },
  {
    code: 1069,
    day: "Possível aguanento de granizo",
    night: "Possível aguanento de granizo",
    icon: 182,
  },
  {
    code: 1072,
    day: "Possível gotejamento congelado",
    night: "Possível gotejamento congelado",
    icon: 185,
  },
  {
    code: 1087,
    day: "Possível tempestade elétrica",
    night: "Possível tempestade elétrica",
    icon: 200,
  },
  {
    code: 1114,
    day: "Neve soprada",
    night: "Neve soprada",
    icon: 227,
  },
  {
    code: 1117,
    day: "Nevasca",
    night: "Nevasca",
    icon: 230,
  },
  {
    code: 1135,
    day: "Neblina densa",
    night: "Neblina densa",
    icon: 248,
  },
  {
    code: 1147,
    day: "Neblina congelante",
    night: "Neblina congelante",
    icon: 260,
  },
  {
    code: 1150,
    day: "Gotejamento leve",
    night: "Gotejamento leve",
    icon: 263,
  },
  {
    code: 1153,
    day: "Chuva leve",
    night: "Chuva leve",
    icon: 266,
  },
  {
    code: 1168,
    day: "Gotejamento congelante",
    night: "Gotejamento congelante",
    icon: 281,
  },
  {
    code: 1171,
    day: "Gotejamento congelante pesado",
    night: "Gotejamento congelante pesado",
    icon: 284,
  },
  {
    code: 1180,
    day: "Chuva leve",
    night: "Chuva leve",
    icon: 293,
  },
  {
    code: 1183,
    day: "Chuva leve",
    night: "Chuva leve",
    icon: 296,
  },
  {
    code: 1186,
    day: "Chuva moderada",
    night: "Chuva moderada",
    icon: 299,
  },
  {
    code: 1189,
    day: "Chuva moderada",
    night: "Chuva moderada",
    icon: 302,
  },
  {
    code: 1192,
    day: "Chuva pesada",
    night: "Chuva pesada",
    icon: 305,
  },
  {
    code: 1195,
    day: "Chuva forte",
    night: "Chuva forte",
    icon: 308,
  },
  {
    code: 1198,
    day: "Gotejamento leve congelante",
    night: "Gotejamento leve congelante",
    icon: 311,
  },
  {
    code: 1201,
    day: "Chuva congelante moderada ou forte",
    night: "Chuva congelante moderada ou forte",
    icon: 314,
  },
  {
    code: 1204,
    day: "Neve leve",
    night: "Neve leve",
    icon: 317,
  },
  {
    code: 1207,
    day: "Neve moderada ou forte",
    night: "Neve moderada ou forte",
    icon: 320,
  },
  {
    code: 1210,
    day: "Neve leve e possível",
    night: "Neve leve e possível",
    icon: 323,
  },
  {
    code: 1213,
    day: "Neve leve",
    night: "Neve leve",
    icon: 326,
  },
  {
    code: 1216,
    day: "Neve moderada possível",
    night: "Neve moderada possível",
    icon: 329,
  },
  {
    code: 1219,
    day: "Neve moderada",
    night: "Neve moderada",
    icon: 332,
  },
  {
    code: 1222,
    day: "Neve leve possível",
    night: "Neve leve possível",
    icon: 335,
  },
  {
    code: 1225,
    day: "Neve forte",
    night: "Neve forte",
    icon: 338,
  },
  {
    code: 1237,
    day: "Pelotas de gelo",
    night: "Pelotas de gelo",
    icon: 350,
  },
  {
    code: 1240,
    day: "Chuva leve",
    night: "Chuva leve",
    icon: 353,
  },
  {
    code: 1243,
    day: "Chuva moderada ou forte",
    night: "Chuva moderada ou forte",
    icon: 356,
  },
  {
    code: 1246,
    day: "Chuva torrencial",
    night: "Chuva torrencial",
    icon: 359,
  },
  {
    code: 1249,
    day: "Chuva leve com granizo",
    night: "Chuva leve com granizo",
    icon: 362,
  },
  {
    code: 1252,
    day: "Chuva moderada ou forte com granizo",
    night: "Chuva moderada ou forte com granizo",
    icon: 365,
  },
  {
    code: 1255,
    day: "Chuva leve com neve",
    night: "Chuva leve com neve",
    icon: 368,
  },
  {
    code: 1258,
    day: "Neve moderada ou forte",
    night: "Neve moderada ou forte",
    icon: 371,
  },
  {
    code: 1261,
    day: "Chuva de pelotas de gelo leve",
    night: "Chuva de pelotas de gelo leve",
    icon: 374,
  },
  {
    code: 1264,
    day: "Chuva moderada ou forte de pelotas de gelo",
    night: "Chuva moderada ou forte de pelotas de gelo",
    icon: 377,
  },
  {
    code: 1273,
    day: "Chuva leve com trovoada",
    night: "Chuva leve com trovoada",
    icon: 386,
  },
  {
    code: 1276,
    day: "Chuva moderada ou forte com trovoada",
    night: "Chuva moderada ou forte com trovoada",
    icon: 389,
  },
  {
    code: 1279,
    day: "Neve leve com trovoada",
    night: "Neve leve com trovoada",
    icon: 392,
  },
  {
    code: 1282,
    day: "Neve moderada ou forte com trovoada",
    night: "Neve moderada ou forte com trovoada",
    icon: 395,
  },
];

export default conditonsData;
